language: ruby
rvm:
  - 2.2.3
  - jruby
before_install: gem install bundler -v 1.10.6

script: 'bundle exec rake'

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^release\/.*$/

notifications:
  email:
    recipients:
      - jeff.carley@gmail.com
    on_failure: change
    on_success: never
