language: ruby
rvm:
  - 2.3.0
  - 2.2.3
  - jruby-head
  - jruby-19mode
  - jruby-9.0.4.0
before_install: gem install bundler -v 1.10.6

env:
  - JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"

script: 'bundle exec rake'

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^release\/.*$/

notifications:
  email:
    recipients:
      - jeff.carley@gmail.com
    on_failure: change
    on_success: never
